name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and zip
      run: |
        npm ci
        npm run build
        npm run zip-ci:dev
        ls
      env:
        CI: true
    - name: upload to chrome store
      uses: trmcnvn/chrome-addon@v1
      with:
        # extension is only necessary when updating an existing addon,
        # omitting it will create a new addon
        zip: build-zip/develop.zip
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
